### ISSUE TITLE
Add sfz highlighting to the Ace editor

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz-webaudio#2]

**Comment by kmturley** [comment]
I'm attempting to write this feature. It requires using the ace codebase to compile custom syntax highlighters.

I have started a fork with the base sfz template here:
https://github.com/kmturley/ace/commit/e50e38a596a054faec0e02a6f32d5349a8ef8c9c

Planning to translate the syntax highlighting regexs from here:
https://github.com/sfz/highlight.js/blob/master/src/sfz.js

Will post updates on my progress here...

**Comment by kmturley** [comment]
There was already a sfz tmLanguage file here:
https://github.com/sfztools/syntax-highlighting-vscode/blob/master/syntaxes/sfz.tmLanguage.json

There is a section on Ace Editor `Using the TMLanguage Tool` showing how to generate the syntax files automatically:
https://ace.c9.io/#nav=higlighter

Then run the build/start command locally and it works!
<img width="958" alt="Screenshot 2023-02-03 at 4 03 58 PM" src="https://user-images.githubusercontent.com/1710493/216732898-8b102605-3dcd-435a-a20a-394a163ed1de.png">

Built changes are here:
https://github.com/kmturley/ace/commit/554aeb277ae37efe9f9acff43f1c1a30df0c67b9

Will open a PR to load these into your project
